service: tx-chef
useDotenv: true
frameworkVersion: ^1.64.1
provider:
  lambdaHashingVersion: 20201221
  name: aws
  profile: tamedia
  region: eu-central-1
  runtime: nodejs14.x
  timeout: 30
  stage: ${opt:stage, 'dev'}
  role: arn:aws:iam::716110578696:role/service-role/info-werdino-lambda-role-gfqzye3q
functions:
  run:
    handler: handler.run
    events:
    - schedule:
        rate: cron(0 7 ? * MON-FRI *)
        enabled: true